### ISSUE TITLE
only html working

### ISSUE THREAD

**Issue by KhaledTurk** [clupasq/word-mastermind#5]
i cloned the project and did as follows:
git clone https://github.com/clupasq/word-mastermind.git
cd word-mastermind
npm start.

the project worked but had 6 boxes for romanian and it does not work. 
i tried to use:
npm audit fix. 
but still the same. 

help me please

**Comment by clupasq** [comment]
Hey, thanks for reporting this!

It was a mistake on my end - I wrote that you could install dependencies with `yarn` or `npm`.
In fact, only `yarn` should be used, because I have a `yarn.lock` file that ensures the correct dependencies are installed.

Please follow the updated docs and let me know if it works for you.

You can install yarn with `npm i -g yarn`.

**Comment by enoughio** [comment]
kh
